### ISSUE TITLE
Standard practice with environments

### ISSUE THREAD

**Issue by tpluscode** [rdfjs-base/environment#4]
I would like to better understand how to best take advantage of the environment, implement factories and combine them in applications. Looking at some examples:

**`@rdfjs/environment`**

This package exports some most common factories. If I wanted to use them I need to create an environment myself:

```js
const env = new Environment([ NamespaceFactory, DataFactory, DatasetFactory ])
```

So far so good, this would be enough to quickly set up the minimal RDF/JS functionalities in a project

Q: Would it make sense to export a default environment from this package so that `new` is not necessary

**Feature packages**

A good example is `@rdfjs/namespace`, because it depends on `DataFactory`. When used in an environment it will use the implementation provided there but it is possible to use it independently, where `@rdfjs/data-model` is imported directly.

Q: Is that the current best practice, to provide the functionalities using the minimal set of factories? Or would you rather recommend that new packages do not directly import any factories and require one being provided in arguments?

**Pre-built environment and extensions**

The only example I'm aware of is `rdf-ext`. It provides an environment pre-packaged with a multitude of factories.

Q: How does one extend an environment with additional factories?

Say, I wished to add a hypothetical factory with the functionalities of `rdf-utils-fs` to `rdf-ext`, without the need to repeat what the latter already does. For example, something like

```js
import rdf from 'rdf-ext'
import FsUtilsFactory from 'rdf-utils-fs/Factory.js`

const extendedEnv = rdf.extend(FsUtilsFactory)
```

The method `.extend` would take the existing factories from the env and add the new ones, like

```
class Environment {
  extend(...factories) {
    return new Environment(this._factories, ...factories)
    // TODO: call `clone` on factories copied from `this`
  }
}
```

Similarly, I could imagine a `merge` method to combine the factories from multiple environments

**Comment by bergos** [comment]
> Q: Would it make sense to export a default environment from this package so that `new` is not necessary

Most factories are defined now in the matching package (e.g., @rdfjs/data-model, @rdfjs/dataset, @rdfjs/namespace). The factories in this package will be removed in the next major version. Therefore it doesn't make sense to export a default environment.

> Q: Is that the current best practice, to provide the functionalities using the minimal set of factories? Or would you rather recommend that new packages do not directly import any factories and require one being provided in arguments?

`@rdfjs/namespace` is like that because of legacy reasons. [shacl-engine](https://github.com/rdf-ext/shacl-engine) would be a better example. It requires a factory argument, and for most cases, that's probably the best option.

But context matters: If it's only a small package like `@rdfjs/data-model` and the objects are not exported for further processing, the `@rdfjs/data-model` could be imported directly.

> Q: How does one extend an environment with additional factories?

Environments should be created only once in the application. Otherwise, you may run into some issues, like overlapping blank node identifiers. I create separate `factory.js` files for that use case and explicitly list all factories used by the environment. For example, the test code in the [shacle-engine](https://github.com/rdf-ext/shacl-engine/blob/master/test/support/factory.js) package is implemented like this. That gives you a better overview of what is actually included in the environment. Also, you do this only once in the application. [rdf-ext](https://github.com/rdf-ext/rdf-ext/blob/master/index.js) exports all factories used in the environment, so you can use them as a starting point. For maintenance reasons, I don't want to extend the environment code + tests for this rare case.

In general: Custom environments are an advanced feature, and I would recommend building an application with `rdf-ext` and switch to a custom environment once you run into issues like bundle size.

**Comment by tpluscode** [comment]
> In general: Custom environments are an advanced feature, and I would recommend building an application with rdf-ext and switch to a custom environment once you run into issues like bundle size.

That is, however, precisely the point. Say I do indeed start with `rdf-ext` and wish to add `shacl-engine/Factory.js`. Do I need to reconstruct the entire environment with the factories I need from `rdf-ext` and include `shacl-engine`?

**Comment by bergos** [comment]
Yes

**Comment by tpluscode** [comment]
Suffice to say that is not exactly dev-friendly

How about extending the `clone` function with a parameter which would be an array of additional factories to add to the new clone?

Or more appropriately, add a `extend` method with such a functionality?

**Comment by bergos** [comment]
I strongly disagree. Adding a lot of magic is just confusing, requires a lot of documentation, and probably will still not prevent making mistakes. Explicitly listing all used factories costs less than ten lines of code and needs to be done only once per application, with the benefit of making the code more readable. Also, the most common use case for creating a custom factory will be reducing bundle size, which requires removing factories, and that would require another method. Therefore, this feature request is rejected.
